image:
  name: hashicorp/terraform
  entrypoint: ['']

variables:
  TF_ROOT: 'terraform/'
  ANSIBLE_ROOT: 'ansible/'
  TF_STATE_NAME: 'terraform.tfstate'
  TF_ADDRESS: 'https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}'
  TF_USERNAME: ${GITLAB_USERNAME}
  TF_PASSWORD: ${TF_ACCESS_TOKEN}
  ANSIBLE_HOST_KEY_CHECKING: 'False'
  HOSTS_FILE: 'hosts'

cache:
  - key: $CI_PIPELINE_ID-terraform-cache
    paths:
      - ${TF_ROOT}/.terraform/
      - ${TF_ROOT}/.terraform.lock.hcl

stages:
  - setup
  - validate
  - infra
  - deploy
  - cleanup

before_script:
  # debug - remove before production
  echo "Debug info"
  - pwd
  - ls -la
  - ls -la ${TF_ROOT}
  - ls -la ${ANSIBLE_ROOT}

check_format:
  stage: setup
  script:
    - terraform fmt
  cache: []
  allow_failure: true

init_backend:
  stage: setup
  before_script:
    - cd ${TF_ROOT}
  script:
    - terraform init
      -backend-config=address=${TF_ADDRESS}
      -backend-config=lock_address=${TF_ADDRESS}/lock
      -backend-config=unlock_address=${TF_ADDRESS}/lock
      -backend-config=username=${TF_USERNAME}
      -backend-config=password=${TF_PASSWORD}
      -backend-config=lock_method=POST
      -backend-config=unlock_method=DELETE
      -backend-config=retry_wait_min=5

check_config:
  stage: validate
  before_script:
    - cd ${TF_ROOT}
  script:
    - terraform validate
  allow_failure: true
  needs:
    - job: init_backend

create_infra:
  stage: infra
  before_script:
    - cd ${TF_ROOT}
    - export TF_VAR_do_token=${DIGITALOCEAN_ACCESS_TOKEN}
    - export TF_VAR_ssh_key=${PUBLIC_SSH_KEY}
  script:
    - terraform apply -auto-approve
  after_script:
    - echo "Exporting droplet IP to Ansible hosts file"
    - DROPLET_IP=$(terraform output -raw droplet_ip)
    - echo "[homolog]" > $HOSTS_FILE
    - echo "$DROPLET_IP" >> $HOSTS_FILE
    - pwd
    - ls -la
  artifacts:
    paths:
      - ./hosts
    expire_in: never
  when: manual
  needs:
    - job: init_backend

setup_infra:
  image: alpinelinux/ansible
  stage: infra
  before_script:
    - cp $HOSTS_FILE $ANSIBLE_ROOT
    - cd $ANSIBLE_ROOT
    - pwd
    - ls -la
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/sige_ed25519
    - chmod 400 ~/.ssh/sige_ed25519
    - chmod 700 ~/.ssh
  script:
    - ansible-playbook -i hosts -l homolog initial_setup.yml --private-key ~/.ssh/sige_ed25519
    - rm -f ~/.ssh/sige_ed25519
  cache: []
  needs:
    - job: create_infra

deploy_homolog:
  image: alpinelinux/ansible
  stage: deploy
  before_script:
    - cp $HOSTS_FILE $ANSIBLE_ROOT
    - cd $ANSIBLE_ROOT
    - pwd
    - ls -la
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/sige_ed25519
    - chmod 400 ~/.ssh/sige_ed25519
    - chmod 700 ~/.ssh
  script:
    - ansible-playbook -i hosts -l homolog deploy_sige.yml --private-key ~/.ssh/sige_ed25519
    - rm -f ~/.ssh/sige_ed25519
  when: manual
  needs:
    - job: setup_infra
  cache: []

deploy_prod:
  image: alpinelinux/ansible
  stage: deploy
  script:
    - echo "Deploying to production"
  when: manual
  needs:
    - job: setup_infra
  cache: []

destroy_infra:
  stage: cleanup
  before_script:
    - cd ${TF_ROOT}
    - export TF_VAR_do_token=${DIGITALOCEAN_ACCESS_TOKEN}
    - export TF_VAR_ssh_key=${PUBLIC_SSH_KEY}
  script:
    - terraform destroy -auto-approve
  when: manual
  needs:
    - job: create_infra
