services:
  uptime-kuma:
    container_name: ${container_name}
    image: ${image}:${image_tag}
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.http.routers.uptime-kuma.rule: "Host(`${hostname}`)"
      traefik.http.services.uptime-kuma.loadbalancer.server.port: ${port}
      traefik.http.routers.uptime-kuma.entrypoints: "websecure"
      traefik.http.routers.uptime-kuma.tls.certresolver: "leprod"
    networks:
        - proxy-network

networks:
    proxy-network:
        name: proxy-network
        external: true
