- name: Install list packages
  hosts: all
  become: true
  vars:
    packages:
      - "htop"
      - "vim"
      - "git"
      - "curl"
      - "wget"
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: "present"
        update_cache: "yes"
      loop: "{{ packages }}"
