services:
  webserver:
    container_name: webserver
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
      - /etc/ssl/_letsencrypt:/etc/ssl/_letsencrypt
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/mediafiles:ro
      - nextjs_static:/app/nextjs_static:ro
    networks:
      - proxy-network

volumes:
  static_volume:
    external: true
  media_volume:
    external: true
  nextjs_static:
    external: true

networks:
  proxy-network:
    external: true
