services:
  portainer:
    container_name: ${container_name}
    image: ${image}:${image_tag}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.rule: "Host(`${hostname}`)"
      traefik.http.services.portainer.loadbalancer.server.port: ${port}
      traefik.http.routers.portainer.entrypoints: "websecure"
      traefik.http.routers.portainer.tls.certresolver: "leprod"
    networks:
      - proxy-network

volumes:
  portainer-data:
    driver: local

networks:
    proxy-network:
        name: proxy-network
        external: true
