services:
  portainer:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE}:${IMAGE_TAG}
    restart: unless-stopped
    expose:
      - ${PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.rule: "Host(`${HOSTNAME}`)"
      traefik.http.services.portainer.loadbalancer.server.port: ${PORT}
      traefik.http.routers.portainer.entrypoints: "websecure"
      traefik.http.routers.portainer.tls.certresolver: "leprod"
    networks:
      - proxy-network

volumes:
  portainer-data:
    driver: local

networks:
    proxy-network:
        name: proxy-network
        external: true
