---
- name: Deploy application using Docker Compose
  hosts: all
  gather_facts: false
  vars_files:
    - host_vars/repository.yml
  tasks:
    - name: Clone or update the repository - branch development
      ansible.builtin.git:
        repo: "{{ sige_master_repo }}"
        dest: "{{ sige_master_path }}"
        clone: true
        update: true
        single_branch: true
        version: "development"
        force: true
      register: git
      notify: Restart containers

  handlers:
    - name: Restart containers
      ansible.builtin.command:
        cmd: "docker compose -f {{ sige_master_path }}/docker-compose.yml up -d --force-recreate"
      listen: "git"
